CREATE TABLE REQUESTER (
	ID BIGINT NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(25) NOT NULL,
    ADDRESS VARCHAR(25) NOT NULL,
    TELEPHONE_NUMBER VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE SUBSCRIPTION (
	ID BIGINT NOT NULL,
	ID_REQUESTER BIGINT NOT NULL,
    CHANNEL VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    FREQUENCY VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
);
ALTER TABLE SUBSCRIPTION
	ADD FOREIGN KEY (ID_REQUESTER) 
	REFERENCES REQUESTER (ID);

CREATE TABLE TARGET (
	ID BIGINT NOT NULL,
    GENDER VARCHAR(25) NOT NULL,
	AGE_FROM INTEGER not null,
	AGE_TO INTEGER not null,
	INCOME_FROM INTEGER not null,
	INCOME_TO INTEGER not null,
	CURRENCY_INCOME VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE SURVEY (
	ID BIGINT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	CATEGORY VARCHAR(255) NOT NULL,
	LANGUAGE VARCHAR(25) NOT NULL,
	DATE_CREATED TIMESTAMP NOT NULL,
	ID_TARGET BIGINT NOT NULL,
	COUNTRY VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);
ALTER TABLE SURVEY
	ADD FOREIGN KEY (ID_TARGET) 
	REFERENCES TARGET (ID);
	
CREATE TABLE QUESTION (
	ID BIGINT NOT NULL,
    HEADING VARCHAR(255) NOT NULL,
    POSITION INTEGER NOT null,
	FAMILY INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
	
CREATE TABLE CONTENT (
	ID BIGINT NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);
	
-- ANSWERS
CREATE TABLE R_QUESTION_CONTENT (
	ID_QUESTION BIGINT NOT NULL,
	ID_CONTENT BIGINT NOT NULL,
	POSITION INTEGER NOT null,
	VISIBLE BOOLEAN,
	REQUIRED BOOLEAN,
    ANSWER_TYPE VARCHAR(255) NOT NULL -- COHICE OR ROW
);
ALTER TABLE R_QUESTION_CONTENT
	ADD FOREIGN KEY (ID_QUESTION) 
	REFERENCES QUESTION (ID);	
ALTER TABLE R_QUESTION_CONTENT
	ADD FOREIGN KEY (ID_CONTENT) 
	REFERENCES CONTENT (ID);	

CREATE TABLE R_SURVEY_QUESTION (
	ID_SURVEY BIGINT NOT NULL,
	ID_QUESTION BIGINT NOT NULL,
	PAGE INTEGER NOT null
);
	
ALTER TABLE R_SURVEY_QUESTION
	ADD FOREIGN KEY (ID_SURVEY) 
	REFERENCES SURVEY (ID);	
ALTER TABLE R_SURVEY_QUESTION
	ADD FOREIGN KEY (ID_QUESTION) 
	REFERENCES QUESTION (ID);